name: dsne
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - scikit-learn
  - scikit-image
  - scipy
  - seaborn
  - tqdm
  - jupyterlab
  - pip
  - pip:
      - mxnet-cu101mkl
      - mxboard
